version: '3'

services:
  app:
    image: node:14.18.1
    ports:
      - '5000:5000'
    volumes:
      - ./:/src
    depends_on:
      - redis
    command: 'node /src/app.js'
  redis:
    image: redis:6.2.6
